### ISSUE TITLE
When deployed by operator, portal cannot read database

### ISSUE THREAD

**Issue by paulczar** [eduk8s/eduk8s-portal#9]
This is on a GCP cluster.

The python binaries are running as user `1001` and the PVC is created without any special permissions which means its only writable by `root`.

I had to edit the deployment and add the following to the pod template to make it work:

```yaml
      securityContext:
        fsGroup: 1001
```

Some clouds (hello IBM) don't support updating the FS permissions via the `securityContext` and would instead need a `initContainer` running as root to `chown | chmod` the PVC contents as appropriate.

**Comment by GrahamDumpleton** [comment]
The need to add that security context can be because a cluster has been set up to match a privileged pod security policy to system:authenticated group. This is actually a quite bad practice and forces the modification of every deployment made to the cluster in order to set the fsGroup. If an appropriate restricted policy was matched by default, which is usually the case when pod security policies is set, fsGroup would be added automatically. What are the names of the pod security policies defined in the cluster? Are any mapped to system:authenticated group via a cluster role binding.

Anyway, this is an issue we are still getting our heads around and we came across something that may at least help in case of deploying the operator and workshops but not what you do in the workshops if workshops use persistent storage. The solution would be to define our own pod security policy which sets things up correctly as needed, rather than being at mercy of what ever system default may be. This still has some problems to workaround Kubernetes priority issues when selecting the pod security policy, but got a solution for that hopefully.

As to IBM clusters, can you give an example of the init container they use? Link to documentation which explains it? Thanks.

**Comment by GrahamDumpleton** [comment]
Some clues for IBM case in:

* https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot_storage

**Comment by GrahamDumpleton** [comment]
Can you try deleting any deployed workshops as well as the operator and reinstall from scratch.

The latest version should deal properly now with the case where a cluster was set up to have system:authenticated group mapped to privileged pod security policy.

If you have a way of testing on the IBM cluster would like to see whether this version handles that as well. The application of pod security policies as am doing now should technically work in place of an init container unless they have the admission controller for pod security policies disabled.

If for some reason the IBM cluster is truly stupid about how they do things and an init container is the only solution even though correct use of pod security policies should work, then have already spec'd out how can handle it in the operator, at least for persistent volumes deployed for portal and workshop sessions by the operator.

**Comment by paulczar** [comment]
Thanks!  This was on a default GKE cluster that I've since deleted, I can spin up a new one and dig into the pod security policies to see if they match up to what you're suggesting, and try a new deploy from head.

as for IBM, I don't have access to any clusters there, I was just using them as an example as I know they don't support `fsGroup`, the link you found is right on the money. I've seen quite a few helm charts that either set `fsGroup` or uses an `initContainer` based on a boolean or a infrastructure provider selection.

**Comment by paulczar** [comment]
Hi I just tried again on a stock GKE cluster and have the same issue. I do see the `psp` created for the portal ui, but I just realized that since GKE doesn't enable PSP admission controller by default, they won't be getting enforced. I'll try turning on PSP and hope nothing else breaks and report back.

**Comment by paulczar** [comment]
I can confirm with the PSP adminission controller enabled, this does in fact work.  Given that many providers still don't enable PSP by default, this is likely to be a common issue and may need to be addressed, even though its not a problem of the eduk8s project itself.

**Comment by GrahamDumpleton** [comment]
Good to know. When I get a chance I will look at adding an option to enable the init container hack and if you have time later and can test that way without psp then would be most helpful. Although, not having psp enabled obviously removes an extra layer of security which is never a good idea.

**Comment by GrahamDumpleton** [comment]
Going to close this issue at this point since psp changes solve it for case where psp admission controller enabled. Have separate issue https://github.com/eduk8s/eduk8s-operator/issues/40 for dealing with possibility of support use of init container later on systems which don't have psp admission controller or that still doesn't work with specific volume types.
